import os
import sys
from pathlib import Path
from datetime import datetime
import json

# Add the project root to the Python path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

class AgentSkills:
    """
    Collection of AI agent skills for the AI Employee system
    """
    
    def __init__(self, vault_path="./AI_Employee_Vault"):
        self.vault_path = Path(vault_path)
        
    def read_file(self, file_path):
        """
        Skill to read a file from the vault
        """
        full_path = self.vault_path / file_path
        
        if full_path.exists():
            content = full_path.read_text(encoding='utf-8')
            return {
                "success": True,
                "content": content,
                "file_path": str(full_path)
            }
        else:
            return {
                "success": False,
                "error": f"File does not exist: {full_path}",
                "file_path": str(full_path)
            }
    
    def write_file(self, file_path, content):
        """
        Skill to write content to a file in the vault
        """
        full_path = self.vault_path / file_path
        
        # Create parent directories if they don't exist
        full_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            return {
                "success": True,
                "file_path": str(full_path),
                "message": f"Successfully wrote to {full_path}"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "file_path": str(full_path)
            }
    
    def move_file(self, source_path, destination_folder):
        """
        Skill to move a file from one location to another in the vault
        """
        source_full_path = self.vault_path / source_path
        dest_folder_path = self.vault_path / destination_folder
        dest_file_path = dest_folder_path / source_path.split('/')[-1]
        
        if not source_full_path.exists():
            return {
                "success": False,
                "error": f"Source file does not exist: {source_full_path}"
            }
        
        # Create destination folder if it doesn't exist
        dest_folder_path.mkdir(parents=True, exist_ok=True)
        
        try:
            source_full_path.rename(dest_file_path)
            
            return {
                "success": True,
                "message": f"Moved {source_path} to {destination_folder}",
                "source_path": str(source_full_path),
                "dest_path": str(dest_file_path)
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def search_files(self, folder_path, pattern="*.md"):
        """
        Skill to search for files in a specific folder
        """
        search_path = self.vault_path / folder_path
        if not search_path.exists():
            return {
                "success": False,
                "error": f"Folder does not exist: {search_path}"
            }
        
        files = list(search_path.glob(pattern))
        file_list = [str(f.relative_to(self.vault_path)) for f in files]
        
        return {
            "success": True,
            "folder": str(search_path),
            "pattern": pattern,
            "files": file_list,
            "count": len(file_list)
        }
    
    def update_dashboard(self, status_updates):
        """
        Skill to update the dashboard with current status
        """
        dashboard_path = self.vault_path / "Dashboard.md"
        
        if dashboard_path.exists():
            content = dashboard_path.read_text()
        else:
            # Create a default dashboard if it doesn't exist
            content = """# AI Employee Dashboard

## Executive Summary
Welcome to your AI Employee dashboard. This system acts as your autonomous digital employee, managing tasks and responsibilities 24/7.

## Current Status
- **AI Employee**: Offline
- **Last Activity**: Never
- **Active Watchers**: 0
- **Pending Actions**: 0

## Recent Activity
- [Never] System not initialized

## Key Metrics
- **Tasks Processed**: 0
- **Messages Handled**: 0
- **Revenue Tracked**: $0.00

## Quick Actions
- [[Company_Handbook]]
- [[Business_Goals]]
- [[Needs_Action]]
- [[Pending_Approval]]

---
*Generated by AI Employee v0.1*
"""
        
        # Update the dashboard content with provided status updates
        lines = content.split('\n')
        updated_lines = []
        
        for line in lines:
            if 'Current Status' in line:
                updated_lines.append(line)
                # Add status updates
                for key, value in status_updates.items():
                    updated_lines.append(f"- **{key}**: {value}")
            else:
                updated_lines.append(line)
        
        # Write updated content back to file
        dashboard_path.write_text('\n'.join(updated_lines))
        
        return {
            "success": True,
            "message": "Dashboard updated successfully",
            "file_path": str(dashboard_path)
        }
    
    def create_action_item(self, title, description, priority="medium", category="general"):
        """
        Skill to create a new action item in the Needs_Action folder
        """
        # Create a unique filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"ACTION_{timestamp}_{title.replace(' ', '_').replace('/', '_')}.md"
        file_path = self.vault_path / "Needs_Action" / filename
        
        # Create the action item content
        content = f"""---
title: {title}
description: {description}
priority: {priority}
category: {category}
created: {datetime.now().isoformat()}
status: pending
---

## Action Required

{description}

### Priority
{priority.capitalize()}

### Category
{category}

### Steps to Complete
- [ ] Review requirements
- [ ] Execute action
- [ ] Verify completion
- [ ] Update status to done

### Related Files
- [[Company_Handbook]]
- [[Business_Goals]]

---
*Created by AI Employee Agent Skill*
*Timestamp: {datetime.now().isoformat()}*
"""
        
        # Write the content to the file
        result = self.write_file(f"Needs_Action/{filename}", content)
        
        return result


def demonstrate_agent_skills():
    """
    Demonstrates the various agent skills
    """
    print("Demonstrating AI Agent Skills...\n")
    
    agent = AgentSkills()
    
    # 1. Create an action item
    print("1. Creating an action item:")
    result = agent.create_action_item(
        "Test Action Item", 
        "This is a test action item created by the AI agent skills.",
        priority="low"
    )
    print(f"Result: {result}\n")
    
    # 2. Search for files in Needs_Action
    print("2. Searching for files in Needs_Action:")
    search_result = agent.search_files("Needs_Action", "*.md")
    print(f"Found {search_result['count']} files: {search_result['files']}\n")
    
    # 3. Read a file (try to read the Company Handbook)
    print("3. Reading Company_Handbook.md:")
    read_result = agent.read_file("Company_Handbook.md")
    if read_result['success']:
        preview = read_result['content'][:200]
        print(f"Successfully read. Preview: {preview}...\n")
    else:
        print(f"Failed to read: {read_result['error']}\n")
    
    # 4. Update dashboard status
    print("4. Updating dashboard status:")
    status_updates = {
        "AI Employee": "Online",
        "Last Activity": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Active Watchers": 1,
        "Pending Actions": search_result['count']
    }
    update_result = agent.update_dashboard(status_updates)
    print(f"Dashboard update result: {update_result['success']}\n")
    
    # 5. Move a file from Needs_Action to Done (create a test file first)
    print("5. Moving a file from Needs_Action to Done:")
    
    # First, create a test file to move
    test_content = "# Test File\n\nThis is a test file for demonstrating the move functionality."
    write_result = agent.write_file("Needs_Action/TEST_MOVE_FILE.md", test_content)
    
    if write_result['success']:
        # Now move the file
        move_result = agent.move_file("Needs_Action/TEST_MOVE_FILE.md", "Done")
        print(f"Move result: {move_result}\n")
    else:
        print(f"Failed to create test file: {write_result['error']}\n")


if __name__ == "__main__":
    demonstrate_agent_skills()