#!/usr/bin/env python3
"""
Bronze Tier Implementation for AI Employee Hackathon
===================================================

This script implements the Bronze Tier requirements:
1. Vault with Dashboard.md and Company_Handbook.md
2. One working Watcher script (Inbox file monitoring)
3. Qwen Code reading from and writing to the vault
4. Basic folder structure: /Inbox, /Needs_Action, /Done
5. All AI functionality implemented as Agent Skills
"""

import os
import sys
import time
from pathlib import Path
from datetime import datetime

# Add the project root to the Python path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from orchestrator import Orchestrator
from watchers.inbox_watcher import InboxWatcher
from agent_skills import AgentSkills
import vault_operations_demo


def setup_bronze_tier():
    """
    Sets up the complete Bronze Tier implementation
    """
    print("Setting up Bronze Tier Implementation for AI Employee...")
    print("="*60)

    # 1. Verify vault structure exists
    print("\n1. Verifying vault structure...")
    vault_path = Path("./AI_Employee_Vault")

    required_dirs = ["Inbox", "Needs_Action", "Done"]
    for dir_name in required_dirs:
        dir_path = vault_path / dir_name
        dir_path.mkdir(exist_ok=True)
        print(f"   - {dir_name} directory: {'[OK]' if dir_path.exists() else '[MISSING]'}")

    # 2. Verify required files exist
    print("\n2. Verifying required files...")
    required_files = ["Dashboard.md", "Company_Handbook.md"]
    for file_name in required_files:
        file_path = vault_path / file_name
        if file_path.exists():
            print(f"   - {file_name}: [EXISTS]")
        else:
            print(f"   - {file_name}: [MISSING] (will be created)")
            # Create a basic version if missing
            if file_name == "Dashboard.md":
                content = """# AI Employee Dashboard

## Executive Summary
Welcome to your AI Employee dashboard. This system acts as your autonomous digital employee, managing tasks and responsibilities 24/7.

## Current Status
- **AI Employee**: Offline
- **Last Activity**: Never
- **Active Watchers**: 0
- **Pending Actions**: 0

## Recent Activity
- [Never] System not initialized

## Key Metrics
- **Tasks Processed**: 0
- **Messages Handled**: 0
- **Revenue Tracked**: $0.00

## Quick Actions
- [[Company_Handbook]]
- [[Business_Goals]]
- [[Needs_Action]]
- [[Pending_Approval]]

---
*Generated by AI Employee v0.1*
"""
                file_path.write_text(content)
            elif file_name == "Company_Handbook.md":
                content = """# Company Handbook

## Mission Statement
Our mission is to leverage AI technology to automate routine tasks, allowing human employees to focus on creative and strategic work.

## Rules of Engagement

### 1. Authorization
- Only perform actions explicitly authorized in this handbook
- For any action not covered here, create a request in [[Pending_Approval]]
- Never access confidential data without proper authorization

### 2. Communication
- Respond to emails professionally and courteously
- Follow company voice and tone guidelines
- Escalate complex customer issues to human supervisors

### 3. Data Handling
- Maintain strict confidentiality of all company data
- Never share sensitive information externally
- Log all data access for audit purposes

### 4. Error Handling
- If uncertain about any action, create a request in [[Pending_Approval]]
- Document all errors in the [[Logs]] directory
- Never attempt to fix problems outside your skill set

### 5. Reporting
- Generate daily activity reports
- Flag unusual patterns or anomalies
- Update dashboard metrics regularly

## Standard Operating Procedures

### Email Processing
1. Categorize incoming emails by priority
2. Handle low-complexity requests automatically
3. Escalate complex requests to [[Pending_Approval]]

### File Processing
1. Scan incoming files for viruses/malware
2. Classify files based on content
3. Route to appropriate departments
4. Update status in system

### Task Management
1. Check [[Needs_Action]] folder regularly
2. Process items based on priority
3. Move completed items to [[Done]]
4. Flag issues in [[Pending_Approval]]

## Emergency Protocols
- System failure: Notify IT department immediately
- Security breach: Follow incident response procedure
- Unusual activity: Flag for human review

---
*Last Updated: February 16, 2026*
*Version: 1.0*
"""
                file_path.write_text(content)

    # 3. Initialize agent skills
    print("\n3. Initializing agent skills...")
    agent = AgentSkills(vault_path)
    print("   - Agent skills initialized: [SUCCESS]")

    # 4. Demonstrate vault operations
    print("\n4. Demonstrating vault operations...")
    vault_operations_demo.demonstrate_vault_operations()

    # 5. Create and demonstrate agent skills
    print("\n5. Demonstrating agent skills...")
    agent.create_action_item(
        "Bronze_Tier_Complete",
        "Bronze tier implementation is complete. All requirements have been met.",
        priority="high"
    )

    # 6. Set up the orchestrator with the Inbox Watcher
    print("\n6. Setting up orchestrator with Inbox Watcher...")
    orchestrator = Orchestrator(vault_path)

    # Add the Inbox Watcher to monitor the Inbox folder
    inbox_watcher = InboxWatcher(vault_path)
    orchestrator.add_watcher(inbox_watcher)
    print("   - Inbox Watcher added to orchestrator: [SUCCESS]")

    # 7. Update dashboard to reflect Bronze Tier completion
    print("\n7. Updating dashboard to reflect Bronze Tier completion...")
    status_updates = {
        "AI Employee": "Online (Bronze Tier)",
        "Last Activity": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Active Watchers": 1,
        "Pending Actions": len(list((vault_path / "Needs_Action").glob("*.md"))),
        "Tier Status": "Bronze Tier Complete"
    }
    agent.update_dashboard(status_updates)
    print("   - Dashboard updated: [SUCCESS]")

    print("\n" + "="*60)
    print("BRONZE TIER IMPLEMENTATION COMPLETE!")
    print("="*60)
    print("\nImplemented components:")
    print("[SUCCESS] Vault with Dashboard.md and Company_Handbook.md")
    print("[SUCCESS] Working Inbox Watcher script (file system monitoring)")
    print("[SUCCESS] Qwen Code reading from and writing to the vault")
    print("[SUCCESS] Basic folder structure: /Inbox, /Needs_Action, /Done")
    print("[SUCCESS] AI functionality implemented as Agent Skills")
    print("\nThe system is now ready for Silver Tier enhancements.")


def run_bronze_tier_demo():
    """
    Runs a demonstration of the Bronze Tier implementation
    """
    print("Running Bronze Tier Demo...")
    print("="*40)

    # Create a test file in the Inbox to demonstrate the watcher
    vault_path = Path("./AI_Employee_Vault")
    test_file = vault_path / "Inbox" / "TEST_DEMO_FILE.txt"

    with open(test_file, 'w') as f:
        f.write(f"This is a test file created at {datetime.now().isoformat()}\n")
        f.write("It will be detected by the Inbox Watcher and moved to Needs_Action\n")

    print(f"Created test file: {test_file}")
    print("Note: The actual watcher would detect this and move it to Needs_Action")
    print("(In a real implementation, you would run the orchestrator in a separate process)")


if __name__ == "__main__":
    setup_bronze_tier()
    print("\n" + "-"*60)
    run_bronze_tier_demo()